[package]
name = "ritlug"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poise = "0.3.0"
dotenv = "0.15"

[dependencies.tokio]
version = "1.0"
features = ["macros", "rt-multi-thread"]
